
left_words = [
    'progressive', 'liberal', 'equality', 'social justice', 'climate action', 
    'green energy', 'civil rights', 'feminism', 'universal healthcare', 'pro-choice',
    'lgbtq rights', 'living wage', 'minimum wage', 'public education', 'affordable housing',
    'labor union', 'gun control', 'diversity', 'inclusion', 'workers\' rights',
    'affirmative action', 'secularism', 'multiculturalism', 'environmentalism', 'global warming',
    'renewable energy', 'peace movement', 'diplomacy', 'human rights', 'income equality',
    'public transport', 'voting rights', 'democratic socialism', 'fair trade', 'social safety net',
    'police reform', 'community organizing', 'grassroots movement', 'political correctness', 'redistribution of wealth',
    'tax fairness', 'anti-racism', 'immigration reform', 'refugee rights', 'gender equality',
    'LGBTQ+ equality', 'marriage equality', 'reproductive rights', 'planned parenthood', 'equal pay',
    'tuition-free college', 'student loan forgiveness', 'clean energy', 'carbon emissions', 'net neutrality',
    'public broadcasting', 'media reform', 'body positivity', 'veganism', 'animal rights',
    'disability rights', 'affordable healthcare', 'Medicare for All', 'public option', 'opioid crisis',
    'homelessness', 'gentrification', 'urban development', 'public art', 'cultural diversity',
    'social enterprise', 'nonprofit sector', 'community development', 'digital divide', 'food security',
    'fair housing', 'tenant rights', 'public parks', 'urban agriculture', 'community gardens',
    'sustainable development', 'public spaces', 'mass transit', 'cycling infrastructure', 'walkability',
    'urban planning', 'smart growth', 'mixed-use development', 'public plazas', 'green urbanism',
    'antifa', 'socialism', 'anarchism', 'collectivism', 'anti-fascism', 'class struggle',
    'revolutionary', 'radical', 'worker\'s control', 'direct action', 'anti-capitalist',
    'eco-socialist', 'communal', 'decolonization', 'anti-imperialism', 'militant',
    'grassroots', 'labor strike', 'radical democracy', 'social justice warrior',
    'class consciousness', 'proletariat', 'bourgeoisie', 'dialectical materialism',
    'Marxism', 'Leninism', 'Maoism', 'Trotskyism', 'Luxemburgism', 'autonomism',
    'left communism', 'libertarian socialism', 'situationism', 'ultra-leftism',
    'left anarchism', 'anarcho-communism', 'anarcho-syndicalism', 'mutualism',
    'social anarchism', 'guild socialism', 'neozapatismo', 'autogestion',
    'participism', 'anticapitalism', 'anti-neoliberalism', 'anti-globalization',
    'solidarity economy', 'workers\' self-management', 'general strike',
    'rent strike', 'landless movement', 'squatting', 'anti-gentrification',
    'housing cooperative', 'food cooperative', 'anti-nuclear movement',
    'climate justice', 'ecofeminism', 'environmental justice', 'degrowth',
    'conservation movement', 'earth liberation', 'animal liberation', 'anti-vivisection',
    'anti-consumerism', 'buy nothing day', 'freeganism', 'simple living',
    'anti-war movement', 'pacifism', 'nonviolence', 'civil disobedience',
    'draft resistance', 'anti-militarism', 'disarmament movement', 'nuclear disarmament',
    'anti-imperialist', 'third-worldism', 'pan-Africanism', 'indigenism',
    'Zapatismo', 'Bolivarianism', 'Alba movement', 'Pink tide', 'alter-globalization',
    'world social forum', 'anti-austerity movement', 'anti-cuts movement',
    'occupy movement', 'indignados movement', 'Arab Spring', 'Black Lives Matter',
    'Me Too movement', 'prison abolition', 'police abolition', 'restorative justice'
]

center_words = [
    'centrist', 'moderate', 'bipartisan', 'middle ground', 'status quo',
    'free market', 'fiscal responsibility', 'pragmatic', 'nonpartisan', 'balanced budget',
    'moderation', 'compromise', 'independent', 'swing voter', 'centrism',
    'market-based', 'economic stability', 'political stability', 'regulatory',
    'business-friendly', 'centrality', 'mainstream', 'traditionalist', 'establishment',
    'incrementalism', 'political moderation', 'political middle', 'median voter', 'centrist democracy',
    'moderate politics', 'centrist policy', 'practical solutions', 'apolitical', 'electoral center',
    'political pragmatism', 'moderate reform', 'consensus politics', 'cross-party', 'middle-of-the-road',
    'political balance', 'sensible center', 'middle path', 'political centrism', 'centrist coalition',
    'moderate viewpoint', 'political neutrality', 'moderate stance', 'centrist approach', 'political middle ground',
    'political mediator', 'balanced approach', 'non-extremist', 'moderate voice', 'politically neutral',
    'centrist platform', 'moderate agenda', 'centrist politics', 'moderate coalition', 'moderate policy',
    'practical politics', 'political realism', 'moderate viewpoint', 'centrist position', 'moderate perspective',
    'centrist perspective', 'political centrality', 'moderate leadership', 'political moderation', 'balanced politics',
    'pragmatic approach', 'moderate opinion', 'centrist opinion', 'moderate leadership', 'centrist leadership',
    'middle-of-the-road policy', 'political balancing', 'pragmatic policy', 'moderate platform', 'centrist consensus',
    'political temperance', 'pragmatic solutions', 'moderate consensus', 'centrist solution', 'political compromise',
    'moderate solution', 'pragmatic centrism', 'centrist pragmatism', 'political centrality', 'balanced policy',
    'centrist policy', 'moderate pragmatism', 'pragmatic politics', 'political middle path', 'balanced view'
]


right_words = [
    'conservative', 'capitalism', 'free market', 'limited government', 'traditional',
    'nationalism', 'pro-life', 'second amendment', 'private property', 'deregulation',
    'tax cuts', 'strong defense', 'border security', 'individualism', 'self-reliance',
    'free enterprise', 'family values', 'small government', 'patriotism', 'law and order',
    'right-wing', 'fiscal conservatism', 'market economy', 'states\' rights', 'personal responsibility',
    'economic freedom', 'property rights', 'religious freedom', 'traditional marriage', 'national sovereignty',
    'constitutionalism', 'judicial restraint', 'balanced budget', 'enterprise', 'self-sufficiency',
    'national pride', 'military strength', 'veterans', 'policing', 'homeland security',
    'anti-communism', 'patriarchal', 'cultural conservatism', 'heritage', 'moral values',
    'christian values', 'supply-side economics', 'monetarism', 'neoconservatism', 'laissez-faire',
    'individual rights', 'second amendment rights', 'gun ownership', 'right to bear arms', 'religious liberty',
    'christian right', 'traditional family', 'nuclear family', 'social conservatism', 'pro-business',
    'economic liberalism', 'capitalist democracy', 'economic individualism', 'market liberalism', 'classical liberalism',
    'entrepreneurship', 'business ethics', 'corporate responsibility', 'economic efficiency', 'privatization',
    'school choice', 'charter schools', 'voucher system', 'education reform', 'academic standards',
    'local control', 'community values', 'civic duty', 'traditional education', 'academic excellence',
    'parental rights', 'family values', 'community service', 'volunteerism', 'civic engagement',
    'patriotic education', 'cultural heritage', 'national identity', 'historical preservation', 'cultural preservation',
    'heritage conservation', 'national history', 'cultural pride', 'patriotic values', 'historical memory',
    'alt-right', 'nationalist', 'authoritarian', 'xenophobia', 'ethno-state',
    'isolationism', 'nativism', 'protectionism', 'anti-immigration', 'ultraconservative',
    'hardline', 'radical traditionalism', 'neo-reactionary', 'far-right', 'anti-globalist',
    'ethnic purity', 'extreme nationalism', 'right-wing populism', 'neo-fascist', 'white identity',
    'white nationalism', 'racial realism', 'identitarian', 'ethnonationalism', 'cultural purity',
    'racial purity', 'blood and soil', 'racial separatism', 'white separatism', 'anti-multiculturalism',
    'anti-Islam', 'anti-Semitic', 'race war', 'white survival', 'racial hierarchy',
    'racial supremacy', 'white power', 'neo-Nazi', 'skinhead', 'racialist',
    'anti-refugee', 'deportation', 'border wall', 'immigration control', 'national purity',
    'ethnic homogeneity', 'cultural homogeneity', 'racial homogeneity', 'racial identity', 'ethnic identity',
    'cultural identity', 'racial pride', 'ethnic pride', 'cultural pride', 'western civilization',
    'eurocentrism', 'western chauvinism', 'white advocacy', 'racial nationalism', 'racialist philosophy',
    'racial integrity', 'ethnic nationalism', 'racial nationalism', 'white separatist', 'white supremacy',
    'racialist ideology', 'white ethnostate', 'white sovereignty', 'racialist movement', 'white traditionalism',
    'white heritage', 'racial heritage', 'ethnic heritage', 'cultural heritage', 'traditionalist movement',
    'racial traditionalism', 'white activism', 'racial activism', 'ethnic activism', 'cultural activism',
    'white consciousness', 'racial consciousness', 'ethnic consciousness', 'cultural consciousness', 'white solidarity',
    'racial solidarity', 'ethnic solidarity', 'cultural solidarity', 'white resistance', 'racial resistance',
    'ethnic resistance', 'cultural resistance', 'white revival', 'racial revival', 'ethnic revival',
    'cultural revival', 'white advocacy group', 'racial advocacy group', 'ethnic advocacy group', 'cultural advocacy group',
    'white defense', 'racial defense', 'ethnic defense', 'cultural defense', 'white interests',
    'racial interests', 'ethnic interests', 'cultural interests', 'white preservation', 'racial preservation',
    'ethnic preservation', 'cultural preservation', 'white rights', 'racial rights', 'ethnic rights',
    'cultural rights', 'white cause', 'racial cause', 'ethnic cause', 'cultural cause'
]

